### PR TITLE
Added photo to homepage

### PR DESCRIPTION
**Pull request by AaronAlexander-debug**
## Description

Added photo to homepage.

Fixes #<number>

## Screenshots
Screen Shot 2021-09-29 at 11 16 51 PM

### CODE REVIEW

**Review by dyang5200 — COMMENTED** [review]
Aaron, your code looks good! However, I think you accidentally committed two .DS_Store files (one in the /client folder and one in the main directory) and also a yarn.lock (this usually happens if you try running `yarn` in the main directory instead of in /client or /api). If you can delete these three files and re-commit, that would be great. Thanks!

First try your best to figure out how to resolve this on your own, but if you have any questions, let me know :)

**Comment by AaronAlexander-debug** [comment]
Okay, so I was able to merge the rest of the commits made by other Academy members onto my branch and everything seems to be going well, but every single time I try to commit the merge, one of the test cases fails (which in this case is always client / client-test push). It says that I lack the 'package-lock.json' file, so I think this is the only issue blocking me from merging...

Screen Shot 2021-10-03 at 7 14 41 PM

**Comment by dyang5200** [comment]
Yup, so this is because you deleted `yarn.lock` in the client folder. Running `yarn install` in client again should fix this issue and allow you to pass the last test. Originally, you had `yarn.lock` in the main academy-sandbox folder, but `yarn.lock` should only be in /client and /api folders, not the main folder.

For some more context, `yarn.lock` defines the dependencies of a project and running `yarn install` generates the `yarn.lock` file.

**Review by dyang5200 — APPROVED** [review]
Amazing :)

**Pull request merged**
